# Generated by Django 3.0.5 on 2021-07-13 21:29

import api.models
import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalControl',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('patientCode', models.CharField(max_length=5)),
                ('controlDate', models.DateField(default=datetime.date.today)),
                ('arrivalDose', models.FloatField(default=0)),
                ('updatedDose', models.FloatField(default=0)),
                ('arrivalINR', models.FloatField(default=0)),
                ('inrInRange', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogWTDparametres',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('p_1', models.FloatField(default=0)),
                ('p_2', models.FloatField(default=0)),
                ('p_3', models.FloatField(default=0)),
                ('p_4', models.FloatField(default=0)),
                ('p_5', models.FloatField(default=0)),
                ('p_6', models.FloatField(default=0)),
                ('p_7', models.FloatField(default=0)),
                ('p_8', models.FloatField(default=0)),
                ('p_9', models.FloatField(default=0)),
                ('p_10', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('sex', models.CharField(max_length=1)),
                ('bloodType', models.CharField(max_length=256)),
                ('initialDate', models.DateField(default=datetime.date.today)),
                ('initialDosis', models.FloatField(default=0)),
                ('initialINR', models.FloatField()),
                ('weeklyDosisInRange', models.FloatField(default=0)),
                ('totalDays', models.IntegerField(default=0)),
                ('weight', models.IntegerField()),
                ('height', models.FloatField()),
                ('imc', models.FloatField()),
                ('age', models.IntegerField(default=0)),
                ('genetics', djongo.models.fields.EmbeddedField(model_container=api.models.Genetic)),
                ('diagnosis', djongo.models.fields.EmbeddedField(model_container=api.models.Diagnosis)),
            ],
        ),
    ]
